AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - bin/*
    - vendor/**/*
    - tmp/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/EmptyBlock:
  Enabled: true
  AllowEmptyLambdas: true

Lint/MissingSuper:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/RedundantConstantBase:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120


Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Naming/MethodParameterName:
  AllowedNames:
    - w
    - db
    - id